version: '3'
services:
   web:
      image: docker-personal-dashboard
      build: .
      command: "node index.js"
      ports: 
         - "4000:4000"
      depends_on: 
         - "mongo"

   mongo:
      image: "mongo"